s3_bucket=ikwilnaardefilm
s3_region=eu-central-1
s3_my_movies_file=my_movies.json
useLive=true
useAws=true
fakeMovieContent=false
access_key=<secret>
access_secret=<secret>
mail.host=smtp.gmail.com
mail.port=465
mail.username=ronald.haring@gmail.com
mail.from=ronald.haring@gmail.com
mail.to=ronald.haring@gmail.com
mail.password=<set as envparam>
quarkus.http.port=9000
quarkus.log.level=INFO
